site_name: mse-mlops-project
repo_url: https://github.com/github_handle/mse-mlops-project
site_url: https://github_handle.github.io/mse-mlops-project
site_description: A short description of the project
site_author: Firstname Lastname
edit_uri: edit/main/docs/
repo_name: github_handle/mse-mlops-project
copyright: Maintained by <a href="https://github_handle.com">github_handle</a>.

nav:
  - Home: index.md
  - Pipeline: pipeline.md
  - Modules: modules.md
  - Notebooks:
      - EDA: notebooks/melanoma_dataset_eda.ipynb
plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_source: true
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
theme:
  name: material
  feature:
    tabs: true
  features:
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/github_handle/mse-mlops-project

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
